spring.application.name=personal-finance-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/personal_finance_tracker
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate

jwt.secret=5d2e9d4e6b6c1d8c7f4e9b1c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4
jwt.expiration=900000